import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'vi' | 'zh' | 'ar' | 'hi' | 'de' | 'it' | 'es' | 'sr' | 'pt' | 'ro';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    appTitle: 'MyEDLs',
    appDescription: 'Extraction intelligente des tâches de chantier par IA',
    appSubtitle: 'Identifiez automatiquement les travaux lors de vos visites immobilières : maisons, appartements, immeubles et commerces',
    uploadImages: 'Photos du bien',
    uploadImagesDesc: 'Prenez des photos lors de votre visite pour identifier les tâches',
    chooseImages: 'Choisir des photos',
    uploadVideos: 'Vidéos du bien',
    uploadVideosDesc: 'Filmez votre visite pour une analyse complète du bien',
    chooseVideos: 'Choisir des vidéos',
    textDescription: 'Description des travaux',
    textDescriptionDesc: 'Décrivez les travaux observés lors de votre visite',
    enterDescription: 'Saisir une description',
    importStructure: 'Importer la structure DSC',
    structureLoaded: 'Structure chargée',
    structureLoadedDesc: 'Votre système de classification DSC est prêt',
    importStructureTitle: 'Importer la structure DSC',
    importStructureDesc: 'Chargez la nomenclature DSC (Familles → Catégories → Sous-catégories)',
    importing: 'Import en cours...',
    importSuccess: 'Structure importée avec succès',
    importError: 'Échec de l\'import',
    extractedTasks: 'Tâches extraites',
    extractedTasksDesc: 'Organisées selon la nomenclature DSC (familles, catégories et sous-catégories)',
    noTasks: 'Aucune tâche pour le moment',
    noTasksDesc: 'Importez des photos, vidéos ou décrivez les travaux observés lors de votre visite pour commencer l\'extraction automatique.',
    analyzing: 'Analyse en cours...',
    analyzingDesc: 'L\'IA analyse votre visite et extrait les tâches de chantier',
    analyzingSubDesc: 'Classification automatique selon la nomenclature DSC',
    extractionSuccess: 'Extraction réussie',
    extractionError: 'Erreur d\'extraction',
    videoProcessing: 'Traitement vidéo',
    videoProcessingDesc: 'L\'analyse vidéo sera bientôt disponible. Utilisez des photos ou des descriptions pour le moment.',
    describeWork: 'Décrivez les travaux observés',
    describeWorkDesc: 'Décrivez en détail les travaux nécessaires identifiés lors de votre visite. Incluez les pièces, l\'état constaté, et les interventions à prévoir.',
    workDescription: 'Description des travaux',
    workDescriptionPlaceholder: 'Ex: Cuisine - Remplacement du plan de travail, installation de nouveaux meubles, réfection de la plomberie, peinture des murs...',
    cancel: 'Annuler',
    extractTasks: 'Extraire les tâches',
    exportPdf: 'Exporter en PDF',
    priorityHigh: 'Priorité haute',
    priorityMedium: 'Priorité moyenne',
    priorityLow: 'Priorité basse',
    renovation: 'Rénovation',
    newBuild: 'Construction neuve',
    adminOnly: 'Réservé aux administrateurs',
  },
  en: {
    appTitle: 'MyEDLs',
    appDescription: 'AI-powered construction task extraction',
    appSubtitle: 'Automatically identify work during property visits: houses, apartments, buildings and businesses',
    uploadImages: 'Property Photos',
    uploadImagesDesc: 'Take photos during your visit to identify tasks',
    chooseImages: 'Choose Images',
    uploadVideos: 'Property Videos',
    uploadVideosDesc: 'Film your visit for a complete property analysis',
    chooseVideos: 'Choose Videos',
    textDescription: 'Work Description',
    textDescriptionDesc: 'Describe the work observed during your visit',
    enterDescription: 'Enter Description',
    importStructure: 'Import DSC Structure',
    structureLoaded: 'Structure Loaded',
    structureLoadedDesc: 'Your DSC classification system is ready',
    importStructureTitle: 'Import DSC Structure',
    importStructureDesc: 'Load DSC nomenclature (Families → Categories → Sub-categories)',
    importing: 'Importing...',
    importSuccess: 'Structure imported successfully',
    importError: 'Import failed',
    extractedTasks: 'Extracted Tasks',
    extractedTasksDesc: 'Organized by DSC nomenclature (families, categories and subcategories)',
    noTasks: 'No tasks yet',
    noTasksDesc: 'Upload photos, videos or describe observed work during your visit to start automatic extraction.',
    analyzing: 'Analyzing...',
    analyzingDesc: 'AI is analyzing your visit and extracting construction tasks',
    analyzingSubDesc: 'Automatic classification according to DSC nomenclature',
    extractionSuccess: 'Extraction successful',
    extractionError: 'Extraction error',
    videoProcessing: 'Video Processing',
    videoProcessingDesc: 'Video analysis will be available soon. Use photos or descriptions for now.',
    describeWork: 'Describe the observed work',
    describeWorkDesc: 'Describe in detail the necessary work identified during your visit. Include rooms, observed condition, and planned interventions.',
    workDescription: 'Work Description',
    workDescriptionPlaceholder: 'Ex: Kitchen - Countertop replacement, new cabinet installation, plumbing renovation, wall painting...',
    cancel: 'Cancel',
    extractTasks: 'Extract Tasks',
    exportPdf: 'Export to PDF',
    priorityHigh: 'High Priority',
    priorityMedium: 'Medium Priority',
    priorityLow: 'Low Priority',
    renovation: 'Renovation',
    newBuild: 'New Build',
    adminOnly: 'Administrators only',
  },
  vi: {
    appTitle: 'MyEDLs',
    appDescription: 'Trích xuất công việc xây dựng thông minh bằng AI',
    appSubtitle: 'Tự động xác định công việc trong các chuyến thăm bất động sản: nhà ở, căn hộ, tòa nhà và doanh nghiệp',
    uploadImages: 'Ảnh bất động sản',
    uploadImagesDesc: 'Chụp ảnh trong chuyến thăm để xác định công việc',
    chooseImages: 'Chọn ảnh',
    uploadVideos: 'Video bất động sản',
    uploadVideosDesc: 'Quay video chuyến thăm để phân tích đầy đủ',
    chooseVideos: 'Chọn video',
    textDescription: 'Mô tả công việc',
    textDescriptionDesc: 'Mô tả công việc quan sát được trong chuyến thăm',
    enterDescription: 'Nhập mô tả',
    importStructure: 'Nhập cấu trúc DSC',
    structureLoaded: 'Đã tải cấu trúc',
    structureLoadedDesc: 'Hệ thống phân loại DSC đã sẵn sàng',
    importStructureTitle: 'Nhập cấu trúc DSC',
    importStructureDesc: 'Tải danh pháp DSC (Họ → Danh mục → Danh mục con)',
    importing: 'Đang nhập...',
    importSuccess: 'Nhập cấu trúc thành công',
    importError: 'Nhập thất bại',
    extractedTasks: 'Công việc đã trích xuất',
    extractedTasksDesc: 'Được tổ chức theo danh pháp DSC (họ, danh mục và danh mục con)',
    noTasks: 'Chưa có công việc nào',
    noTasksDesc: 'Tải lên ảnh, video hoặc mô tả công việc quan sát để bắt đầu trích xuất tự động.',
    analyzing: 'Đang phân tích...',
    analyzingDesc: 'AI đang phân tích chuyến thăm và trích xuất công việc xây dựng',
    analyzingSubDesc: 'Phân loại tự động theo danh pháp DSC',
    extractionSuccess: 'Trích xuất thành công',
    extractionError: 'Lỗi trích xuất',
    videoProcessing: 'Xử lý video',
    videoProcessingDesc: 'Phân tích video sẽ sớm có sẵn. Hãy sử dụng ảnh hoặc mô tả.',
    describeWork: 'Mô tả công việc quan sát',
    describeWorkDesc: 'Mô tả chi tiết công việc cần thiết được xác định trong chuyến thăm. Bao gồm phòng, tình trạng quan sát và can thiệp dự kiến.',
    workDescription: 'Mô tả công việc',
    workDescriptionPlaceholder: 'VD: Nhà bếp - Thay mặt bàn, lắp tủ mới, sửa hệ thống ống nước, sơn tường...',
    cancel: 'Hủy',
    extractTasks: 'Trích xuất công việc',
    exportPdf: 'Xuất PDF',
    priorityHigh: 'Ưu tiên cao',
    priorityMedium: 'Ưu tiên trung bình',
    priorityLow: 'Ưu tiên thấp',
    renovation: 'Cải tạo',
    newBuild: 'Xây dựng mới',
    adminOnly: 'Chỉ quản trị viên',
  },
  zh: {
    appTitle: 'MyEDLs',
    appDescription: 'AI智能建筑任务提取',
    appSubtitle: '在房地产访问期间自动识别工作：房屋、公寓、建筑物和企业',
    uploadImages: '房产照片',
    uploadImagesDesc: '在访问期间拍照以识别任务',
    chooseImages: '选择图片',
    uploadVideos: '房产视频',
    uploadVideosDesc: '拍摄访问视频以进行完整的房产分析',
    chooseVideos: '选择视频',
    textDescription: '工作描述',
    textDescriptionDesc: '描述访问期间观察到的工作',
    enterDescription: '输入描述',
    importStructure: '导入DSC结构',
    structureLoaded: '结构已加载',
    structureLoadedDesc: '您的DSC分类系统已准备就绪',
    importStructureTitle: '导入DSC结构',
    importStructureDesc: '加载DSC命名法（家族→类别→子类别）',
    importing: '正在导入...',
    importSuccess: '成功导入结构',
    importError: '导入失败',
    extractedTasks: '已提取任务',
    extractedTasksDesc: '按DSC命名法组织（家族、类别和子类别）',
    noTasks: '暂无任务',
    noTasksDesc: '上传照片、视频或描述访问期间观察到的工作以开始自动提取。',
    analyzing: '正在分析...',
    analyzingDesc: 'AI正在分析您的访问并提取建筑任务',
    analyzingSubDesc: '根据DSC命名法自动分类',
    extractionSuccess: '提取成功',
    extractionError: '提取错误',
    videoProcessing: '视频处理',
    videoProcessingDesc: '视频分析即将推出。请暂时使用照片或描述。',
    describeWork: '描述观察到的工作',
    describeWorkDesc: '详细描述访问期间确定的必要工作。包括房间、观察到的状况和计划干预。',
    workDescription: '工作描述',
    workDescriptionPlaceholder: '例：厨房 - 台面更换、新橱柜安装、管道翻新、墙面粉刷...',
    cancel: '取消',
    extractTasks: '提取任务',
    exportPdf: '导出PDF',
    priorityHigh: '高优先级',
    priorityMedium: '中优先级',
    priorityLow: '低优先级',
    renovation: '翻新',
    newBuild: '新建',
    adminOnly: '仅限管理员',
  },
  ar: {
    appTitle: 'MyEDLs',
    appDescription: 'استخراج مهام البناء الذكية بالذكاء الاصطناعي',
    appSubtitle: 'تحديد العمل تلقائيًا أثناء زيارات العقارات: المنازل والشقق والمباني والأعمال',
    uploadImages: 'صور العقار',
    uploadImagesDesc: 'التقط صورًا أثناء زيارتك لتحديد المهام',
    chooseImages: 'اختر الصور',
    uploadVideos: 'فيديوهات العقار',
    uploadVideosDesc: 'قم بتصوير زيارتك لتحليل كامل للعقار',
    chooseVideos: 'اختر الفيديوهات',
    textDescription: 'وصف العمل',
    textDescriptionDesc: 'صف العمل المُلاحظ أثناء زيارتك',
    enterDescription: 'أدخل الوصف',
    importStructure: 'استيراد هيكل DSC',
    structureLoaded: 'تم تحميل الهيكل',
    structureLoadedDesc: 'نظام التصنيف DSC جاهز',
    importStructureTitle: 'استيراد هيكل DSC',
    importStructureDesc: 'تحميل تسمية DSC (العائلات ← الفئات ← الفئات الفرعية)',
    importing: 'جاري الاستيراد...',
    importSuccess: 'تم استيراد الهيكل بنجاح',
    importError: 'فشل الاستيراد',
    extractedTasks: 'المهام المستخرجة',
    extractedTasksDesc: 'منظمة حسب تسمية DSC (العائلات والفئات والفئات الفرعية)',
    noTasks: 'لا توجد مهام حتى الآن',
    noTasksDesc: 'قم بتحميل الصور أو الفيديوهات أو وصف العمل المُلاحظ أثناء زيارتك لبدء الاستخراج التلقائي.',
    analyzing: 'جاري التحليل...',
    analyzingDesc: 'الذكاء الاصطناعي يحلل زيارتك ويستخرج مهام البناء',
    analyzingSubDesc: 'التصنيف التلقائي وفقًا لتسمية DSC',
    extractionSuccess: 'الاستخراج ناجح',
    extractionError: 'خطأ في الاستخراج',
    videoProcessing: 'معالجة الفيديو',
    videoProcessingDesc: 'سيتوفر تحليل الفيديو قريبًا. استخدم الصور أو الأوصاف في الوقت الحالي.',
    describeWork: 'صف العمل المُلاحظ',
    describeWorkDesc: 'صف بالتفصيل العمل الضروري المُحدد أثناء زيارتك. اذكر الغرف والحالة المُلاحظة والتدخلات المخططة.',
    workDescription: 'وصف العمل',
    workDescriptionPlaceholder: 'مثال: المطبخ - استبدال سطح العمل، تركيب خزائن جديدة، تجديد السباكة، طلاء الجدران...',
    cancel: 'إلغاء',
    extractTasks: 'استخراج المهام',
    exportPdf: 'تصدير PDF',
    priorityHigh: 'أولوية عالية',
    priorityMedium: 'أولوية متوسطة',
    priorityLow: 'أولوية منخفضة',
    renovation: 'تجديد',
    newBuild: 'بناء جديد',
    adminOnly: 'للمسؤولين فقط',
  },
  hi: {
    appTitle: 'MyEDLs',
    appDescription: 'AI-संचालित निर्माण कार्य निष्कर्षण',
    appSubtitle: 'संपत्ति के दौरे के दौरान स्वचालित रूप से काम की पहचान करें: घर, अपार्टमेंट, भवन और व्यवसाय',
    uploadImages: 'संपत्ति की तस्वीरें',
    uploadImagesDesc: 'कार्यों की पहचान करने के लिए अपने दौरे के दौरान तस्वीरें लें',
    chooseImages: 'तस्वीरें चुनें',
    uploadVideos: 'संपत्ति के वीडियो',
    uploadVideosDesc: 'पूर्ण संपत्ति विश्लेषण के लिए अपने दौरे का वीडियो बनाएं',
    chooseVideos: 'वीडियो चुनें',
    textDescription: 'कार्य विवरण',
    textDescriptionDesc: 'अपने दौरे के दौरान देखे गए कार्य का वर्णन करें',
    enterDescription: 'विवरण दर्ज करें',
    importStructure: 'DSC संरचना आयात करें',
    structureLoaded: 'संरचना लोड की गई',
    structureLoadedDesc: 'आपकी DSC वर्गीकरण प्रणाली तैयार है',
    importStructureTitle: 'DSC संरचना आयात करें',
    importStructureDesc: 'DSC नामकरण लोड करें (परिवार → श्रेणियां → उप-श्रेणियां)',
    importing: 'आयात हो रहा है...',
    importSuccess: 'संरचना सफलतापूर्वक आयात की गई',
    importError: 'आयात विफल',
    extractedTasks: 'निकाले गए कार्य',
    extractedTasksDesc: 'DSC नामकरण द्वारा व्यवस्थित (परिवार, श्रेणियां और उप-श्रेणियां)',
    noTasks: 'अभी तक कोई कार्य नहीं',
    noTasksDesc: 'स्वचालित निष्कर्षण शुरू करने के लिए तस्वीरें, वीडियो अपलोड करें या अपने दौरे के दौरान देखे गए कार्य का वर्णन करें।',
    analyzing: 'विश्लेषण हो रहा है...',
    analyzingDesc: 'AI आपके दौरे का विश्लेषण कर रहा है और निर्माण कार्य निकाल रहा है',
    analyzingSubDesc: 'DSC नामकरण के अनुसार स्वचालित वर्गीकरण',
    extractionSuccess: 'निष्कर्षण सफल',
    extractionError: 'निष्कर्षण त्रुटि',
    videoProcessing: 'वीडियो प्रोसेसिंग',
    videoProcessingDesc: 'वीडियो विश्लेषण जल्द ही उपलब्ध होगा। अभी के लिए तस्वीरों या विवरण का उपयोग करें।',
    describeWork: 'देखे गए कार्य का वर्णन करें',
    describeWorkDesc: 'अपने दौरे के दौरान पहचाने गए आवश्यक कार्य का विस्तार से वर्णन करें। कमरे, देखी गई स्थिति और नियोजित हस्तक्षेप शामिल करें।',
    workDescription: 'कार्य विवरण',
    workDescriptionPlaceholder: 'उदाहरण: रसोई - काउंटरटॉप प्रतिस्थापन, नए कैबिनेट स्थापना, प्लंबिंग नवीनीकरण, दीवार पेंटिंग...',
    cancel: 'रद्द करें',
    extractTasks: 'कार्य निकालें',
    exportPdf: 'PDF निर्यात करें',
    priorityHigh: 'उच्च प्राथमिकता',
    priorityMedium: 'मध्यम प्राथमिकता',
    priorityLow: 'कम प्राथमिकता',
    renovation: 'नवीनीकरण',
    newBuild: 'नया निर्माण',
    adminOnly: 'केवल प्रशासक',
  },
  de: {
    appTitle: 'MyEDLs',
    appDescription: 'KI-gesteuerte Bauaufgabenextraktion',
    appSubtitle: 'Identifizieren Sie automatisch Arbeiten bei Immobilienbesichtigungen: Häuser, Wohnungen, Gebäude und Unternehmen',
    uploadImages: 'Immobilienfotos',
    uploadImagesDesc: 'Machen Sie Fotos während Ihrer Besichtigung, um Aufgaben zu identifizieren',
    chooseImages: 'Bilder auswählen',
    uploadVideos: 'Immobilienvideos',
    uploadVideosDesc: 'Filmen Sie Ihre Besichtigung für eine vollständige Immobilienanalyse',
    chooseVideos: 'Videos auswählen',
    textDescription: 'Arbeitsbeschreibung',
    textDescriptionDesc: 'Beschreiben Sie die während Ihrer Besichtigung beobachtete Arbeit',
    enterDescription: 'Beschreibung eingeben',
    importStructure: 'DSC-Struktur importieren',
    structureLoaded: 'Struktur geladen',
    structureLoadedDesc: 'Ihr DSC-Klassifizierungssystem ist bereit',
    importStructureTitle: 'DSC-Struktur importieren',
    importStructureDesc: 'DSC-Nomenklatur laden (Familien → Kategorien → Unterkategorien)',
    importing: 'Importiere...',
    importSuccess: 'Struktur erfolgreich importiert',
    importError: 'Import fehlgeschlagen',
    extractedTasks: 'Extrahierte Aufgaben',
    extractedTasksDesc: 'Nach DSC-Nomenklatur organisiert (Familien, Kategorien und Unterkategorien)',
    noTasks: 'Noch keine Aufgaben',
    noTasksDesc: 'Laden Sie Fotos oder Videos hoch oder beschreiben Sie beobachtete Arbeiten während Ihrer Besichtigung, um die automatische Extraktion zu starten.',
    analyzing: 'Analysiere...',
    analyzingDesc: 'KI analysiert Ihre Besichtigung und extrahiert Bauaufgaben',
    analyzingSubDesc: 'Automatische Klassifizierung nach DSC-Nomenklatur',
    extractionSuccess: 'Extraktion erfolgreich',
    extractionError: 'Extraktionsfehler',
    videoProcessing: 'Videoverarbeitung',
    videoProcessingDesc: 'Videoanalyse wird bald verfügbar sein. Verwenden Sie vorerst Fotos oder Beschreibungen.',
    describeWork: 'Beschreiben Sie die beobachtete Arbeit',
    describeWorkDesc: 'Beschreiben Sie detailliert die während Ihrer Besichtigung identifizierten notwendigen Arbeiten. Fügen Sie Räume, beobachteten Zustand und geplante Eingriffe hinzu.',
    workDescription: 'Arbeitsbeschreibung',
    workDescriptionPlaceholder: 'Beispiel: Küche - Arbeitsplattenaustausch, neue Schränke installieren, Sanitärrenovierung, Wände streichen...',
    cancel: 'Abbrechen',
    extractTasks: 'Aufgaben extrahieren',
    exportPdf: 'PDF exportieren',
    priorityHigh: 'Hohe Priorität',
    priorityMedium: 'Mittlere Priorität',
    priorityLow: 'Niedrige Priorität',
    renovation: 'Renovierung',
    newBuild: 'Neubau',
    adminOnly: 'Nur Administratoren',
  },
  it: {
    appTitle: 'MyEDLs',
    appDescription: 'Estrazione intelligente di attività di costruzione con IA',
    appSubtitle: 'Identifica automaticamente i lavori durante le visite immobiliari: case, appartamenti, edifici e attività commerciali',
    uploadImages: 'Foto della proprietà',
    uploadImagesDesc: 'Scatta foto durante la tua visita per identificare le attività',
    chooseImages: 'Scegli immagini',
    uploadVideos: 'Video della proprietà',
    uploadVideosDesc: 'Filma la tua visita per un\'analisi completa della proprietà',
    chooseVideos: 'Scegli video',
    textDescription: 'Descrizione del lavoro',
    textDescriptionDesc: 'Descrivi il lavoro osservato durante la tua visita',
    enterDescription: 'Inserisci descrizione',
    importStructure: 'Importa struttura DSC',
    structureLoaded: 'Struttura caricata',
    structureLoadedDesc: 'Il tuo sistema di classificazione DSC è pronto',
    importStructureTitle: 'Importa struttura DSC',
    importStructureDesc: 'Carica la nomenclatura DSC (Famiglie → Categorie → Sottocategorie)',
    importing: 'Importazione in corso...',
    importSuccess: 'Struttura importata con successo',
    importError: 'Importazione fallita',
    extractedTasks: 'Attività estratte',
    extractedTasksDesc: 'Organizzate per nomenclatura DSC (famiglie, categorie e sottocategorie)',
    noTasks: 'Nessuna attività ancora',
    noTasksDesc: 'Carica foto, video o descrivi i lavori osservati durante la tua visita per iniziare l\'estrazione automatica.',
    analyzing: 'Analisi in corso...',
    analyzingDesc: 'L\'IA sta analizzando la tua visita ed estraendo le attività di costruzione',
    analyzingSubDesc: 'Classificazione automatica secondo la nomenclatura DSC',
    extractionSuccess: 'Estrazione riuscita',
    extractionError: 'Errore di estrazione',
    videoProcessing: 'Elaborazione video',
    videoProcessingDesc: 'L\'analisi video sarà presto disponibile. Usa foto o descrizioni per ora.',
    describeWork: 'Descrivi il lavoro osservato',
    describeWorkDesc: 'Descrivi in dettaglio il lavoro necessario identificato durante la tua visita. Includi stanze, condizioni osservate e interventi pianificati.',
    workDescription: 'Descrizione del lavoro',
    workDescriptionPlaceholder: 'Es: Cucina - Sostituzione piano di lavoro, installazione nuovi armadi, ristrutturazione impianto idraulico, pittura pareti...',
    cancel: 'Annulla',
    extractTasks: 'Estrai attività',
    exportPdf: 'Esporta PDF',
    priorityHigh: 'Alta priorità',
    priorityMedium: 'Media priorità',
    priorityLow: 'Bassa priorità',
    renovation: 'Ristrutturazione',
    newBuild: 'Nuova costruzione',
    adminOnly: 'Solo amministratori',
  },
  es: {
    appTitle: 'MyEDLs',
    appDescription: 'Extracción inteligente de tareas de construcción con IA',
    appSubtitle: 'Identifica automáticamente trabajos durante visitas inmobiliarias: casas, apartamentos, edificios y negocios',
    uploadImages: 'Fotos de la propiedad',
    uploadImagesDesc: 'Tome fotos durante su visita para identificar tareas',
    chooseImages: 'Elegir imágenes',
    uploadVideos: 'Videos de la propiedad',
    uploadVideosDesc: 'Filme su visita para un análisis completo de la propiedad',
    chooseVideos: 'Elegir videos',
    textDescription: 'Descripción del trabajo',
    textDescriptionDesc: 'Describa el trabajo observado durante su visita',
    enterDescription: 'Ingresar descripción',
    importStructure: 'Importar estructura DSC',
    structureLoaded: 'Estructura cargada',
    structureLoadedDesc: 'Su sistema de clasificación DSC está listo',
    importStructureTitle: 'Importar estructura DSC',
    importStructureDesc: 'Cargar nomenclatura DSC (Familias → Categorías → Subcategorías)',
    importing: 'Importando...',
    importSuccess: 'Estructura importada exitosamente',
    importError: 'Importación fallida',
    extractedTasks: 'Tareas extraídas',
    extractedTasksDesc: 'Organizadas por nomenclatura DSC (familias, categorías y subcategorías)',
    noTasks: 'Aún no hay tareas',
    noTasksDesc: 'Cargue fotos, videos o describa los trabajos observados durante su visita para iniciar la extracción automática.',
    analyzing: 'Analizando...',
    analyzingDesc: 'La IA está analizando su visita y extrayendo tareas de construcción',
    analyzingSubDesc: 'Clasificación automática según nomenclatura DSC',
    extractionSuccess: 'Extracción exitosa',
    extractionError: 'Error de extracción',
    videoProcessing: 'Procesamiento de video',
    videoProcessingDesc: 'El análisis de video estará disponible pronto. Use fotos o descripciones por ahora.',
    describeWork: 'Describa el trabajo observado',
    describeWorkDesc: 'Describa en detalle el trabajo necesario identificado durante su visita. Incluya habitaciones, condición observada e intervenciones planificadas.',
    workDescription: 'Descripción del trabajo',
    workDescriptionPlaceholder: 'Ej: Cocina - Reemplazo de encimera, instalación de nuevos gabinetes, renovación de plomería, pintura de paredes...',
    cancel: 'Cancelar',
    extractTasks: 'Extraer tareas',
    exportPdf: 'Exportar PDF',
    priorityHigh: 'Alta prioridad',
    priorityMedium: 'Prioridad media',
    priorityLow: 'Baja prioridad',
    renovation: 'Renovación',
    newBuild: 'Nueva construcción',
    adminOnly: 'Solo administradores',
  },
  sr: {
    appTitle: 'MyEDLs',
    appDescription: 'AI екстракција грађевинских задатака',
    appSubtitle: 'Аутоматски идентификујте радове током посета некретнина: куће, станови, зграде и пословни објекти',
    uploadImages: 'Фотографије некретнине',
    uploadImagesDesc: 'Направите фотографије током посете да идентификујете задатке',
    chooseImages: 'Изаберите слике',
    uploadVideos: 'Видео снимци некретнине',
    uploadVideosDesc: 'Снимите вашу посету за потпуну анализу некретнине',
    chooseVideos: 'Изаберите видео',
    textDescription: 'Опис рада',
    textDescriptionDesc: 'Опишите рад уочен током ваше посете',
    enterDescription: 'Унесите опис',
    importStructure: 'Увези DSC структуру',
    structureLoaded: 'Структура учитана',
    structureLoadedDesc: 'Ваш DSC систем класификације је спреман',
    importStructureTitle: 'Увези DSC структуру',
    importStructureDesc: 'Учитајте DSC номенклатуру (Породице → Категорије → Поткатегорије)',
    importing: 'Увоз у току...',
    importSuccess: 'Структура успешно увезена',
    importError: 'Увоз није успео',
    extractedTasks: 'Извучени задаци',
    extractedTasksDesc: 'Организовано према DSC номенклатури (породице, категорије и поткатегорије)',
    noTasks: 'Још нема задатака',
    noTasksDesc: 'Отпремите фотографије, видео снимке или опишите уочене радове током посете да започнете аутоматску екстракцију.',
    analyzing: 'Анализа у току...',
    analyzingDesc: 'AI анализира вашу посету и извлачи грађевинске задатке',
    analyzingSubDesc: 'Аутоматска класификација према DSC номенклатури',
    extractionSuccess: 'Успешна екстракција',
    extractionError: 'Грешка при екстракцији',
    videoProcessing: 'Обрада видео снимка',
    videoProcessingDesc: 'Анализа видео снимака биће ускоро доступна. Користите фотографије или описе за сада.',
    describeWork: 'Опишите уочени рад',
    describeWorkDesc: 'Детаљно опишите потребне радове идентификоване током ваше посете. Укључите просторије, уочено стање и планиране интервенције.',
    workDescription: 'Опис рада',
    workDescriptionPlaceholder: 'Нпр: Кухиња - Замена радне површине, монтажа нових ормара, реновирање водовода, бојење зидова...',
    cancel: 'Откажи',
    extractTasks: 'Извуци задатке',
    exportPdf: 'Извези PDF',
    priorityHigh: 'Висок приоритет',
    priorityMedium: 'Средњи приоритет',
    priorityLow: 'Низак приоритет',
    renovation: 'Реновирање',
    newBuild: 'Нова изградња',
    adminOnly: 'Само администратори',
  },
  pt: {
    appTitle: 'MyEDLs',
    appDescription: 'Extração inteligente de tarefas de construção com IA',
    appSubtitle: 'Identifique automaticamente trabalhos durante visitas imobiliárias: casas, apartamentos, prédios e negócios',
    uploadImages: 'Fotos do imóvel',
    uploadImagesDesc: 'Tire fotos durante sua visita para identificar tarefas',
    chooseImages: 'Escolher imagens',
    uploadVideos: 'Vídeos do imóvel',
    uploadVideosDesc: 'Filme sua visita para uma análise completa do imóvel',
    chooseVideos: 'Escolher vídeos',
    textDescription: 'Descrição do trabalho',
    textDescriptionDesc: 'Descreva o trabalho observado durante sua visita',
    enterDescription: 'Digite a descrição',
    importStructure: 'Importar estrutura DSC',
    structureLoaded: 'Estrutura carregada',
    structureLoadedDesc: 'Seu sistema de classificação DSC está pronto',
    importStructureTitle: 'Importar estrutura DSC',
    importStructureDesc: 'Carregar nomenclatura DSC (Famílias → Categorias → Subcategorias)',
    importing: 'Importando...',
    importSuccess: 'Estrutura importada com sucesso',
    importError: 'Importação falhou',
    extractedTasks: 'Tarefas extraídas',
    extractedTasksDesc: 'Organizadas por nomenclatura DSC (famílias, categorias e subcategorias)',
    noTasks: 'Ainda não há tarefas',
    noTasksDesc: 'Envie fotos, vídeos ou descreva os trabalhos observados durante sua visita para iniciar a extração automática.',
    analyzing: 'Analisando...',
    analyzingDesc: 'A IA está analisando sua visita e extraindo tarefas de construção',
    analyzingSubDesc: 'Classificação automática de acordo com a nomenclatura DSC',
    extractionSuccess: 'Extração bem-sucedida',
    extractionError: 'Erro de extração',
    videoProcessing: 'Processamento de vídeo',
    videoProcessingDesc: 'A análise de vídeo estará disponível em breve. Use fotos ou descrições por enquanto.',
    describeWork: 'Descreva o trabalho observado',
    describeWorkDesc: 'Descreva detalhadamente o trabalho necessário identificado durante sua visita. Inclua cômodos, condição observada e intervenções planejadas.',
    workDescription: 'Descrição do trabalho',
    workDescriptionPlaceholder: 'Ex: Cozinha - Substituição de bancada, instalação de novos armários, renovação de encanamento, pintura de paredes...',
    cancel: 'Cancelar',
    extractTasks: 'Extrair tarefas',
    exportPdf: 'Exportar PDF',
    priorityHigh: 'Alta prioridade',
    priorityMedium: 'Prioridade média',
    priorityLow: 'Baixa prioridade',
    renovation: 'Renovação',
    newBuild: 'Nova construção',
    adminOnly: 'Somente administradores',
  },
  ro: {
    appTitle: 'MyEDLs',
    appDescription: 'Extragere inteligentă a sarcinilor de construcție cu IA',
    appSubtitle: 'Identificați automat lucrările în timpul vizitelor imobiliare: case, apartamente, clădiri și afaceri',
    uploadImages: 'Fotografii proprietate',
    uploadImagesDesc: 'Faceți fotografii în timpul vizitei pentru a identifica sarcinile',
    chooseImages: 'Alegeți imagini',
    uploadVideos: 'Videoclipuri proprietate',
    uploadVideosDesc: 'Filmați vizita pentru o analiză completă a proprietății',
    chooseVideos: 'Alegeți videoclipuri',
    textDescription: 'Descrierea lucrării',
    textDescriptionDesc: 'Descrieți lucrarea observată în timpul vizitei',
    enterDescription: 'Introduceți descrierea',
    importStructure: 'Importați structura DSC',
    structureLoaded: 'Structură încărcată',
    structureLoadedDesc: 'Sistemul dvs. de clasificare DSC este gata',
    importStructureTitle: 'Importați structura DSC',
    importStructureDesc: 'Încărcați nomenclatura DSC (Familii → Categorii → Subcategorii)',
    importing: 'Se importă...',
    importSuccess: 'Structură importată cu succes',
    importError: 'Importul a eșuat',
    extractedTasks: 'Sarcini extrase',
    extractedTasksDesc: 'Organizate după nomenclatura DSC (familii, categorii și subcategorii)',
    noTasks: 'Încă nu există sarcini',
    noTasksDesc: 'Încărcați fotografii, videoclipuri sau descrieți lucrările observate în timpul vizitei pentru a începe extragerea automată.',
    analyzing: 'Se analizează...',
    analyzingDesc: 'IA analizează vizita dvs. și extrage sarcinile de construcție',
    analyzingSubDesc: 'Clasificare automată conform nomenclaturii DSC',
    extractionSuccess: 'Extragere reușită',
    extractionError: 'Eroare de extragere',
    videoProcessing: 'Procesare video',
    videoProcessingDesc: 'Analiza video va fi disponibilă în curând. Folosiți fotografii sau descrieri deocamdată.',
    describeWork: 'Descrieți lucrarea observată',
    describeWorkDesc: 'Descrieți în detaliu lucrarea necesară identificată în timpul vizitei. Includeți camere, condiția observată și intervențiile planificate.',
    workDescription: 'Descrierea lucrării',
    workDescriptionPlaceholder: 'Ex: Bucătărie - Înlocuire blat, instalare dulapuri noi, renovare instalație sanitară, vopsire pereți...',
    cancel: 'Anulare',
    extractTasks: 'Extrage sarcini',
    exportPdf: 'Exportă PDF',
    priorityHigh: 'Prioritate mare',
    priorityMedium: 'Prioritate medie',
    priorityLow: 'Prioritate mică',
    renovation: 'Renovare',
    newBuild: 'Construcție nouă',
    adminOnly: 'Doar administratori',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};