// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mobileStorage } from '@/lib/mobileStorage';
import { capacitorFetch } from '@/lib/capacitorFetch';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validation des variables d'environnement
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  
  throw new Error(
    `Variables d'environnement Supabase manquantes: ${missing.join(', ')}\n` +
    'Vérifiez que le fichier .env.local existe et contient ces variables.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Utilise mobileStorage qui s'adapte automatiquement à web (localStorage) ou mobile (Capacitor Preferences)
// Compteur pour limiter les tentatives de rafraîchissement en cas d'erreur réseau
let refreshTokenFailureCount = 0;
const MAX_REFRESH_FAILURES = 3;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: mobileStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (url, options = {}) => {
      const urlString = typeof url === 'string' ? url : url.toString();
      const method = options.method || 'GET';
      
      // Log toutes les requêtes Supabase pour debug (en dev ou si erreur)
      const isAuthRequest = urlString.includes('/auth/v1/');
      const isRefreshRequest = urlString.includes('token') && method === 'POST';
      
      if (isRefreshRequest) {
        console.log('[Supabase] Refresh token attempt:', urlString.substring(0, 100));
      }
      
      // Utilise capacitorFetch dans Capacitor, fetch natif sur web
      const fetchImpl = Capacitor.isNativePlatform() ? capacitorFetch : fetch;
      
      // Fait la requête et gère les erreurs
      return fetchImpl(url, options)
        .then((response) => {
          // Réinitialise le compteur en cas de succès
          if (isRefreshRequest && response.ok) {
            refreshTokenFailureCount = 0;
          }
          return response;
        })
        .catch((error) => {
          // Pour les erreurs de rafraîchissement, on limite les tentatives
          if (isRefreshRequest) {
            refreshTokenFailureCount++;
            if (refreshTokenFailureCount >= MAX_REFRESH_FAILURES) {
              console.warn('[Supabase] Too many refresh failures, stopping auto-refresh attempts');
              // Crée une Response avec status 503 pour indiquer que le service est indisponible
              // Cela évite le RangeError et permet à Supabase de gérer l'erreur correctement
              return new Response(
                JSON.stringify({ 
                  error: 'Network unavailable',
                  message: 'Unable to refresh token: network error',
                }),
                {
                  status: 503,
                  statusText: 'Service Unavailable',
                  headers: { 'Content-Type': 'application/json' },
                }
              );
            }
          }
          
          console.error('[Supabase Fetch Error]', {
            url: urlString.substring(0, 150),
            method: method,
            error: error.message,
            isAuthRequest,
            isRefreshRequest,
            isNative: Capacitor.isNativePlatform(),
            refreshFailureCount: isRefreshRequest ? refreshTokenFailureCount : undefined,
          });
          
          // Pour les autres erreurs, on les propage normalement
          throw error;
        });
    },
  },
});

// Log des variables d'environnement au démarrage (toujours pour debug mobile)
console.log('🔍 Supabase Config:', {
  url: SUPABASE_URL || 'MANQUANT',
  urlPreview: SUPABASE_URL?.substring(0, 50) + '...',
  keyPreview: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...',
  hasUrl: !!SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  envMode: import.meta.env.MODE,
  allEnvKeys: Object.keys(import.meta.env).filter(k => k.startsWith('VITE_')),
});

// Avertissement si les variables sont manquantes
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ ERREUR CRITIQUE: Variables Supabase manquantes!');
  console.error('Vérifiez que .env.local existe et contient:');
  console.error('  VITE_SUPABASE_URL=https://...');
  console.error('  VITE_SUPABASE_PUBLISHABLE_KEY=eyJ...');
  console.error('Puis relancez: npm run build && npm run cap:sync');
}